import React, { useState, useEffect } from 'react';
import { supabase } from '../supabase';
import { AppUser, UserRole, BRANCHES } from '../types';
import { Users, UserPlus, Trash2, Edit2, Shield, X, Check, Power, PowerOff } from 'lucide-react';
import { toast } from 'sonner';
import { logAction } from '../lib/logger';

const UserManager: React.FC = () => {
  const [users, setUsers] = useState<AppUser[]>([]);
  const [loading, setLoading] = useState(true);
  const [isEditing, setIsEditing] = useState(false);
  const [editingEmail, setEditingEmail] = useState('');
  
  const [formData, setFormData] = useState<Partial<AppUser>>({
    email: '',
    role: 'salesperson',
    name: '',
    branchId: '',
    isActive: true
  });

  useEffect(() => {
    const fetchUsers = async () => {
      const { data, error } = await supabase.from('users').select('*');
      if (data) {
        setUsers(data.map((d: any) => ({
          email: d.email,
          role: d.role,
          name: d.name,
          branchId: d.branch_id,
          isActive: d.is_active,
          createdAt: d.created_at
        })));
      }
      setLoading(false);
    };

    fetchUsers();

    const channel = supabase.channel('users-changes')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'users' }, payload => {
        fetchUsers();
      })
      .subscribe();

    return () => { supabase.removeChannel(channel); };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.email || !formData.role) {
      toast.error('يرجى إدخال البريد الإلكتروني والصلاحية');
      return;
    }

    try {
      const email = formData.email.toLowerCase().trim();
      const userData = {
        email: email,
        role: formData.role,
        name: formData.name || '',
        branch_id: formData.branchId || null,
        is_active: formData.isActive ?? true
      };

      if (!isEditing) {
        // Check if user already exists (maybe they already signed in once)
        const { data: existingUser } = await supabase
          .from('users')
          .select('id')
          .eq('email', userData.email)
          .maybeSingle();

        if (existingUser) {
          // User exists (maybe signed in before), just update their role/branch
          const { error } = await supabase.from('users').update({
            role: userData.role,
            name: userData.name,
            branch_id: userData.branch_id,
            is_active: userData.is_active
          }).eq('email', userData.email);
          if (error) throw error;
        } else {
          // Pre-register user - id will be auto-generated by DB (uuid_generate_v4 default)
          const { error } = await supabase.from('users').insert([{
            email: userData.email,
            role: userData.role,
            name: userData.name,
            branch_id: userData.branch_id,
            is_active: userData.is_active
            // id auto-generated by uuid_generate_v4() default
          }]);
          if (error) throw error;
        }
      } else {
        const { error } = await supabase.from('users').update({
           role: userData.role,
           name: userData.name,
           branch_id: userData.branch_id,
           is_active: userData.is_active
        }).eq('email', editingEmail);
        if (error) throw error;
      }
      
      await logAction(isEditing ? 'تعديل مستخدم' : 'إضافة مستخدم', `تم ${isEditing ? 'تعديل' : 'إضافة'} المستخدم: ${formData.email}`, formData.branchId);
      toast.success(isEditing ? 'تم تحديث بيانات المستخدم بنجاح' : 'تم إضافة المستخدم بنجاح. دعه يسجل دخوله ليكتمل الربط.');
      resetForm();
    } catch (error: any) {
      console.error("Error saving user:", error);
      toast.error(error.message || 'حدث خطأ أثناء حفظ المستخدم');
    }
  };

  const handleEdit = (user: AppUser) => {
    setFormData({
      email: user.email,
      role: user.role,
      name: user.name || '',
      branchId: user.branchId || '',
      isActive: user.isActive
    });
    setEditingEmail(user.email);
    setIsEditing(true);
  };

  const handleDelete = async (email: string) => {
    if (email === 'szater600@gmail.com' || email === 'sika63123@gmail.com') {
      toast.error('لا يمكن حذف المدير الرئيسي');
      return;
    }
    
    if (window.confirm('هل أنت متأكد من حذف هذا المستخدم نهائياً؟')) {
      try {
        const { error } = await supabase.from('users').delete().eq('email', email);
        if (error) throw error;
        await logAction('حذف مستخدم', `تم حذف المستخدم: ${email}`);
        toast.success('تم حذف المستخدم بنجاح');
      } catch (error: any) {
        console.error("Error deleting user:", error);
        toast.error('حدث خطأ أثناء حذف المستخدم');
      }
    }
  };

  const toggleActive = async (user: AppUser) => {
    if (user.email === 'szater600@gmail.com' || user.email === 'sika63123@gmail.com') {
      toast.error('لا يمكن إيقاف حساب المدير الرئيسي');
      return;
    }

    try {
      const { error } = await supabase.from('users').update({
        is_active: !user.isActive,
      }).eq('email', user.email);
      if (error) throw error;

      await logAction('تغيير حالة مستخدم', `تم ${user.isActive ? 'إيقاف' : 'تفعيل'} حساب المستخدم: ${user.email}`, user.branchId);
      toast.success(user.isActive ? 'تم إيقاف الحساب' : 'تم تفعيل الحساب');
    } catch (error: any) {
      console.error("Error toggling user status:", error);
      toast.error('حدث خطأ أثناء تغيير حالة الحساب');
    }
  };

  const resetForm = () => {
    setFormData({
      email: '',
      role: 'salesperson',
      name: '',
      branchId: '',
      isActive: true
    });
    setIsEditing(false);
    setEditingEmail('');
  };

  const getRoleName = (role: string) => {
    switch (role) {
      case 'admin': return 'مدير نظام';
      case 'manager': return 'مدير';
      case 'pricing': return 'مسؤول أسعار';
      case 'cashier': return 'كاشير';
      case 'salesperson': return 'بائع';
      case 'audit': return 'مراقب';
      default: return role;
    }
  };

  const getRoleColor = (role: string) => {
    switch (role) {
      case 'admin': return 'bg-purple-100 text-purple-800 border-purple-200';
      case 'manager': return 'bg-indigo-100 text-indigo-800 border-indigo-200';
      case 'pricing': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'cashier': return 'bg-green-100 text-green-800 border-green-200';
      case 'salesperson': return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'audit': return 'bg-teal-100 text-teal-800 border-teal-200';
      default: return 'bg-slate-100 text-slate-800 border-slate-200';
    }
  };

  return (
    <div className="p-6 max-w-7xl mx-auto">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-12 h-12 bg-purple-100 text-purple-600 rounded-xl flex items-center justify-center">
          <Shield className="w-6 h-6" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-slate-800">إدارة الصلاحيات والمستخدمين</h1>
          <p className="text-slate-500">إضافة وتعديل صلاحيات الموظفين في النظام</p>
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Form Section */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 sticky top-6">
            <h2 className="text-lg font-bold text-slate-800 mb-6 flex items-center gap-2">
              {isEditing ? <Edit2 className="w-5 h-5 text-blue-500" /> : <UserPlus className="w-5 h-5 text-blue-500" />}
              {isEditing ? 'تعديل بيانات المستخدم' : 'إضافة مستخدم جديد'}
            </h2>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">البريد الإلكتروني (Gmail)</label>
                <input
                  type="email"
                  required
                  disabled={isEditing}
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition disabled:bg-slate-100 disabled:text-slate-500"
                  placeholder="example@gmail.com"
                  dir="ltr"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">الاسم (اختياري)</label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition"
                  placeholder="اسم الموظف"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">الصلاحية</label>
                <select
                  required
                  value={formData.role}
                  onChange={(e) => setFormData({ ...formData, role: e.target.value as UserRole })}
                  className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition bg-white"
                >
                  <option value="salesperson">بائع</option>
                  <option value="cashier">كاشير</option>
                  <option value="pricing">مسؤول أسعار</option>
                  <option value="manager">مدير</option>
                  <option value="admin">مدير نظام (Admin)</option>
                  <option value="audit">مراقب نظام</option>
                </select>
              </div>

              {(formData.role === 'salesperson' || formData.role === 'cashier') && (
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">الفرع (اختياري)</label>
                  <select
                    value={formData.branchId}
                    onChange={(e) => setFormData({ ...formData, branchId: e.target.value })}
                    className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition bg-white"
                  >
                    <option value="">-- بدون فرع محدد --</option>
                    {BRANCHES.map(branch => (
                      <option key={branch.id} value={branch.id}>{branch.name}</option>
                    ))}
                  </select>
                </div>
              )}

              <div className="pt-4 flex gap-3">
                <button
                  type="submit"
                  className="flex-1 bg-blue-600 text-white font-bold py-3 px-4 rounded-xl hover:bg-blue-700 transition flex items-center justify-center gap-2"
                >
                  {isEditing ? <Check className="w-5 h-5" /> : <UserPlus className="w-5 h-5" />}
                  {isEditing ? 'حفظ التعديلات' : 'إضافة المستخدم'}
                </button>
                
                {isEditing && (
                  <button
                    type="button"
                    onClick={resetForm}
                    className="bg-slate-100 text-slate-600 font-bold py-3 px-4 rounded-xl hover:bg-slate-200 transition flex items-center justify-center"
                    title="إلغاء التعديل"
                  >
                    <X className="w-5 h-5" />
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>

        {/* Users List Section */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="p-6 border-b border-slate-200 flex justify-between items-center bg-slate-50">
              <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                <Users className="w-5 h-5 text-blue-600" />
                المستخدمين المسجلين ({users.length})
              </h2>
            </div>
            
            <div className="overflow-x-auto">
              <table className="w-full text-right">
                <thead className="bg-slate-50 border-b border-slate-200 text-slate-600 text-sm">
                  <tr>
                    <th className="p-4 font-semibold">المستخدم</th>
                    <th className="p-4 font-semibold">الصلاحية</th>
                    <th className="p-4 font-semibold">الفرع</th>
                    <th className="p-4 font-semibold">الحالة</th>
                    <th className="p-4 font-semibold text-center">إجراءات</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {loading ? (
                    <tr>
                      <td colSpan={5} className="p-8 text-center text-slate-500">جاري التحميل...</td>
                    </tr>
                  ) : users.length === 0 ? (
                    <tr>
                      <td colSpan={5} className="p-8 text-center text-slate-500">لا يوجد مستخدمين مسجلين</td>
                    </tr>
                  ) : (
                    users.map((user) => (
                      <tr key={user.email} className={`hover:bg-slate-50 transition ${!user.isActive ? 'opacity-60' : ''}`}>
                        <td className="p-4">
                          <div className="font-medium text-slate-800" dir="ltr">{user.email}</div>
                          {user.name && <div className="text-sm text-slate-500">{user.name}</div>}
                        </td>
                        <td className="p-4">
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${getRoleColor(user.role)}`}>
                            {getRoleName(user.role)}
                          </span>
                        </td>
                        <td className="p-4 text-sm text-slate-600">
                          {user.branchId ? BRANCHES.find(b => b.id === user.branchId)?.name || user.branchId : '-'}
                        </td>
                        <td className="p-4">
                          <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-medium ${user.isActive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'}`}>
                            {user.isActive ? 'نشط' : 'موقوف'}
                          </span>
                        </td>
                        <td className="p-4">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => toggleActive(user)}
                              className={`p-2 rounded-lg transition ${user.isActive ? 'text-orange-500 hover:bg-orange-50' : 'text-green-500 hover:bg-green-50'}`}
                              title={user.isActive ? 'إيقاف الحساب' : 'تفعيل الحساب'}
                            >
                              {user.isActive ? <PowerOff className="w-4 h-4" /> : <Power className="w-4 h-4" />}
                            </button>
                            <button
                              onClick={() => handleEdit(user)}
                              className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
                              title="تعديل"
                            >
                              <Edit2 className="w-4 h-4" />
                            </button>
                            <button
                              onClick={() => handleDelete(user.email)}
                              className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition"
                              title="حذف"
                            >
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default UserManager;
